### PR TITLE
1: Adding Elastic as a datastore option

### PR DESCRIPTION
**Pull request by wcchristian**
# Description
Issue #1 Adding elastic as a datastore option.
* You can configure the index to store recipes
* You can configure the index to store executions
* You can configure the elastic instance to store this data
* Because execution data is stored in elastic, you can create dashboards and visualizations based on alerts (or even alert on alerts for that matter).

Looks like I can't add reviewers so I'll just tag you here :) @diogolmenezes

### CODE REVIEW

**Comment by diogolmenezes** [comment]
Hi ! Nice work!
I am thinking about remove the mongo feature and use only your elastic search solution.
I Think it will be more simple to future users understand only one connection type. What do you think about this ?
If you agree, i will accept your work and do the modifications.

**Comment by wcchristian** [comment]
I like that idea!

**Comment by diogolmenezes** [comment]
Awesome! So i will work on it now.

I send you a messege when a finish it!

**Comment by wcchristian** [comment]
Sick!

**Comment by diogolmenezes** [comment]
Hello @wcchristian ! I just removed the mongo support, actually recording the settings in elastic got much better!

Thank you for your help! The improvements are already in the master!

**Pull request merged**
